MIN_TEMP = 0
MAX_TEMP = 45
MIN_SOC = 20
MAX_SOC = 80
MIN_CHARGE_RATE = 0.1 #assumption
MAX_CHARGE_RATE = 0.8
min_values = MIN_TEMP, MIN_SOC , MIN_CHARGE_RATE
max_values = MAX_TEMP, MAX_SOC , MAX_CHARGE_RATE
Parameter_count = 3 
Parameter_name =  ("Temparature","SOC","Charge Rate")